source 'https://github.com/ietstudio/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
# use_frameworks!

target 'AdvertiseVungle_Example' do
  platform :ios, '8.0'
  pod 'AdvertiseVungle', :path => '../'
end
